# 自动求导实验

对函数：
$$
y=2 \pmb x^T\pmb x
$$
求梯度

In [4]:
import torch

x=torch.arange(4.0)
x,x.size()

(tensor([0., 1., 2., 3.]), torch.Size([4]))

指示需要梯度

In [2]:
x.requires_grad_(True)
print(x.grad)

None


In [5]:
y=2*torch.dot(x,x)
y,y.size()

(tensor(28.), torch.Size([]))

反向传播 求导

In [6]:
y.backward()
x.grad

tensor([ 0.,  4.,  8., 12.])

试试另一个函数

In [7]:
x.grad.zero_()
y=x.sum()
y.backward()
x.grad

tensor([1., 1., 1., 1.])